# Generated by Django 5.0.6 on 2024-06-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pricedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='is_start_value',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
