# Generated by Django 5.0.6 on 2024-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_description_pricedata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
