# Generated by Django 5.0.6 on 2024-06-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pricedata_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricedata',
            old_name='value',
            new_name='price',
        ),
    ]
