# Generated by Django 5.0.6 on 2024-06-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_has_free_amount_pricedata_has_free_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
