# Generated by Django 5.0.6 on 2024-06-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pricedata_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
