# Generated by Django 5.0.6 on 2024-06-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pricedata_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
