# Generated by Django 5.0.6 on 2024-06-28 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_pricedata_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='place_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.placetype'),
        ),
    ]
