# Generated by Django 5.0.6 on 2024-07-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_pricedata_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='extra_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
